ccflags-y					+= -Wall -Werror

obj-$(CONFIG_SX_TIME_BOOTSTRAP)	+= sx_time_bootstrap.o

obj-$(CONFIG_SX_SIMPLE_MMAP)	+= simple_mmap.o simple_mmap_sysfs.o \
	simple_mmap_dma.o

obj-$(CONFIG_SX_PUSH_PULL) += pushpull.o

obj-$(CONFIG_SX_CATSON_SCP) += catson_scp.o

obj-$(CONFIG_SX_CATSON_FUSE) += sx_catson_fuse.o

